baseURL = "https://docs.duendesoftware.com/identityserver/v6"
languageCode = "en-us"
title = "Duende IdentityServer Documentation"

theme = "hugo-theme-learn"
# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
editURL = "https://github.com/DuendeSoftware/docs.duendesoftware.com/edit/main/IdentityServer/v6/docs/content/"
qs_base = "https://github.com/DuendeSoftware/Samples/tree/main/IdentityServer/v6/Quickstarts"
samples_base = "https://github.com/DuendeSoftware/Samples/tree/main/IdentityServer/v6"

[markup.goldmark.renderer]
unsafe= true